# This is a basic workflow to help you get started with Actions
name: Cloud Function loadBQ CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ dev ]
    paths: [CloudFunctions/aligator/microservices/loadBQ/src/**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - id: 'auth-dev'
        if: endsWith(github.ref, '/dev')
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CICD_CREDENTIALS_AH584312 }}
      - uses: ./.github/actions/set-environment-variables
        name: SetEnv
      - id: deploy-dev
        if: endsWith(github.ref, '/dev')
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: loadBQ
          runtime: go116
          entry_point: LoadBQ
          region: europe-west1
          memory_mb: 128
          source_dir: CloudFunction/aligator/microservices/loadBQ/src/
          env_vars_file: CloudFunction/aligator/microservices/loadBQ/envs/env_vars_dev.yaml
          timeout: 540
          max_instances: 5
          service_account_email: ah584312@appspot.gserviceaccount.com
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/ah584312/topics/load_bq