# This is a basic workflow to help you get started with Actions
name: Cloud Function main CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ dev ]
    paths: [CloudFunctions/aligator/microservices/main/src/**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - id: 'auth-dev'
        if: endsWith(github.ref, '/dev')
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CICD_CREDENTIALS_AH584312 }}
      - id: deploy-dev
        if: endsWith(github.ref, '/dev')
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: Aligator
          runtime: go116
          entry_point: Aligator
          region: europe-west1
          memory_mb: 256
          source_dir: CloudFunction/aligator/microservices/main/src/
          env_vars_file: CloudFunction/aligator/microservices/main/envs/env_vars_dev.yaml
          ingress_settings: ALLOW_ALL
          timeout: 540
          max_instances: 5
          service_account_email: ${{ env.SERVICE_ACCOUNT_CF_EMAIL }}
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: projects/${{ env.GCP_PROJECT }}/buckets/${{ env.BUCKET-INGEST }}
          event_trigger_service: storage.googleapis.com