# This is a basic workflow to help you get started with Actions
name: st aligator web CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ dev ]
    paths: [CloudFunction/aligator/web/**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell      
      - uses: actions/checkout@v2
      # set up google DEV credentials and project for futures steps
      - name: Set up Cloud SDK DEV
        if: endsWith(github.ref, '/dev')
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CICD_CREDENTIALS_AH584312 }}
          export_default_credentials: true
      # Set variables depending on the modified branch
      - uses: ./.github/actions/set-evironnement-variables
        name: SetEnv
      # Upload plugins and dags folder to GCS
      - name: Use gsutil rsync
        run: |
          gsutil -m rsync -r -c CloudFunction/aligator/web gs://${{ env.BUCKET-WEB }}